#!/usr/bin/env python3

import argparse
import sys

import isoform2
from isoform2 import Locus
from grimoire.genome import Reader

parser = argparse.ArgumentParser(
	description='Alternative isoform generator with NMD')
parser.add_argument('fasta', type=str, metavar='<fasta file>',
	help='input fasta file (reads only the first sequence if multi-fasta) '
	'only for difalt gffs')
parser.add_argument('model', type=str, metavar='<splice model>',
	help='input splicemodel file')
parser.add_argument('--gff', required=False, type=str,
	metavar='<file>', help='gff with wormbase annotations')
parser.add_argument('--out', help='save to named output file')
parser.add_argument('--min_intron', required=False, type=int, default=35,
	metavar='<int>', help='minimum length of intron [%(default)i]')
parser.add_argument('--min_exon', required=False, type=int, default=25,
	metavar='<int>', help='minimum length exon [%(default)i]')
parser.add_argument('--flank', required=False, type=int, default=99,
	metavar='<int>', help='genomic flank on each side [%(default)i]')
parser.add_argument('--limit', required=False, type=int, default=100,
	metavar='<int>', help='limit number of transcripts [%(default)i]')
parser.add_argument('--wdon', required=False, type=float, default=1.0,
	metavar='<float>', help='donor weight [%(default).2f]')
parser.add_argument('--wacc', required=False, type=float, default=1.0,
	metavar='<float>', help='acceptor weight [%(default).2f]')
parser.add_argument('--wexs', required=False, type=float, default=1.0,
	metavar='<float>', help='exon sequence weight [%(default).2f]')
parser.add_argument('--wins', required=False, type=float, default=1.0,
	metavar='<float>', help='intron sequence weight [%(default).2f]')
parser.add_argument('--wexl', required=False, type=float, default=1.0,
	metavar='<float>', help='exon length weight [%(default).2f]')
parser.add_argument('--winl', required=False, type=float, default=1.0,
	metavar='<float>', help='intron length weight [%(default).2f]')
parser.add_argument('--winf', required=False, type=float, default=1.0,
	metavar='<float>', help='intron frequency weight [%(default).2f]')
parser.add_argument('--translate', metavar='<gff>',
	help='translate transcripts and reduce nmd/non-stop targets')
parser.add_argument('--nonstop', type=float, default=1e-3,
	help='degredation from no stop codon [%(default)g]')
parser.add_argument('--nmd', type=float, default=1e-3,
	help='degredation from NMD [%(default)g]')
parser.add_argument('--countonly', action='store_true',
	help='report the total number of isoforms')

arg = parser.parse_args()

model = isoform2.read_splicemodel(arg.model)

weights = {
	'wacc': arg.wacc,
	'wdon': arg.wdon,
	'wexs': arg.wexs,
	'wins': arg.wins,
	'wexl': arg.wexl,
	'winl': arg.winl,
	'winf': arg.winf,
}

constraints = {
	'min_intron': arg.min_intron,
	'min_exon': arg.min_exon,
	'flank': arg.flank
}

if arg.out: fp = open(arg.out, 'w')
else: fp = sys.stdout

name, seq = next(isoform2.read_fasta(arg.fasta))
locus = Locus(name, seq, model, constraints=constraints, weights=weights,
	limit=arg.limit)

if arg.translate:
	
	# get sub-region and whole gene coordinates
	reg_beg, reg_end = None, None
	gen_beg, gen_end = None, None
	with open(arg.fasta, 'rt') as fa_fp:
		for line in fa_fp:
			if line.startswith('>'):
				line = line.rstrip()
				line = line.split(' ')
				reg = line[1].split(':')[1].split('-')
				reg_beg, reg_end = int(reg[0]), int(reg[1])
				gen = line[4].split(':')[1].split('-')
				gen_beg, gen_end = int(gen[0]), int(gen[1])
				
	# find canonical gene structure 'a'
	CDSs = {}
	with open(arg.translate, 'rt') as gff_fp:
		total_len = 0
		ex_count = 0
		for line in gff_fp:
			line = line.rstrip().split('\t')
			# maybe move this filter to search_gff.py?
			if (line[2] == 'CDS' 
				and line[8].split(';')[0].split(':')[1].endswith('a')):
					beg, end = int(line[3]), int(line[4])
					cds_len = end-beg+1
					total_len += cds_len
					CDSs[(beg, end)] = [cds_len, line[7]]

	CDSs = dict(sorted(CDSs.items(), key=lambda item: item[0][0]))
	
	# find truncated canonical CDS structure
	cds_struct = {}
	
	middle_exon = False	
	first_exon = False
	for item in CDSs.items():
		if first_exon == True:
			middle_exon = True
			first_exon == False
		if reg_beg >= int(item[0][0]) and reg_beg <= int(item[0][1]):
			first_exon = True
			cds_struct[item[0]] = item[1]
		if reg_end <= int(item[0][1]) and reg_end >= int(item[0][0]):
			middle_exon = False
			cds_struct[item[0]] = item[1]
		if middle_exon == True:
			first_exon = False
			cds_struct[item[0]] = item[1]
			
	# adjust coordinates so sub region starts at 0
	cds_struct_2 = {}
	for item in cds_struct.items():
		cds_struct_2[(item[0][0]-reg_beg), (item[0][1]-reg_beg)] = item[1]

	for item in cds_struct_2.items():
		print(item)

	'''
	# adjust coors
	for iso in locus.isoforms:
		adj_exons = []
		for exon in iso.exons:
			adj_exon = (exon[0]+reg_beg, exon[1]+reg_beg)
			adj_exons.append(adj_exon)
		iso.exons = adj_exons
	'''
		
	# all first exons start at the same position
	# remove flank for testing, need to add into the fasta files
	for iso in locus.isoforms:
		ex_ct = 1
		codons = []
		# build cds_seq, then break into codons
		cds_seq = []
		for iso_exon in iso.exons:
			if ex_ct == 1:
				first_ex = next(iter(cds_struct_2))
				last_ex = next(reversed(cds_struct_2))
				print(first_ex, last_ex, '###')
				print(first_ex[1], iso_exon[0], iso_exon)
				cds_start = first_ex[0] - int(cds_struct_2[first_ex][1])
				frame_start = abs(cds_start%3)+1
				codon = seq[frame_start:frame_start+3]
				print(codon, frame_start, '#')
				print(iso_exon, '@@')
				#for i in range(abs(frame_start%3)
				for i in range(frame_start, iso_exon[1], 3):
					codon = seq[i:i+3]
					print(codon, i)
				ex_ct += 1
			else: 
				print(iso_exon)
				#for i in range(iso_exon[0], iso_exon[
			
		break
		
	print(seq[2])
	print(seq[82])
	
	print(seq)



	# what phase is reg beg? look at first exon seen by APC
	
	minejc = 10
	minutr = 300
	
	# need to find non-stops and distance of stop codon from EJC
	

	# examine the isoforms to determine if they are NMD targets
	prevs = [iso.prob for iso in locus.isoforms]
	posts = []
	rtypes = []

	
			

	'''
	# need to give translate() last in frame codon?
	for iso in locus.isoforms:
		iso.translate(cds_beg)
		if   iso.rnatype == 'non-stop':   iso.prob *= arg.nonstop
		elif iso.rnatype == 'nmd-target': iso.prob *= arg.nmd
		posts.append(iso.prob)
		rtypes.append(iso.rnatype)
	'''
	# probabilities before adjusting for NMD
	#print(prevs)
	# probabilities after adjusting for NMD
	#print(posts)
	# can be coding, non-stop, or nmd-target
	#print(rtypes)
	'''
		
	'''
	# can't assume upstream exon structure from truncated isoforms
	# need to use first CDS in gff for correct reading frame

	# CDS txs don't always appear in order, see unc-16
	'''
	cds_lines = {}
	seen_tx = []
	with open(arg.translate, 'rt') as gff_fp:
		for line in gff_fp:
			line = line.rstrip().split('\t')
			if line[2] == 'CDS':
				txs = line[8].split(';')[1].split('=')[1].split(',')
				tx_id = tuple([x.split(':')[1] for x in txs])[0]
				print(tx_id)
				seen_tx.append(tx_id)
				if tx_id not in cds_lines:
					cds_lines[tx_id] = [line]
				else:
					cds_lines[tx_id].append(line)
				
	#for item in cds_lines.items():
	#	print(item)
		
	print(set(seen_tx))
	# pick first tx
	first_tx = sorted(set(seen_tx), key=lambda x: x.split('.')[1:])[0]
	print(first_tx)
	print('@')
	print('@')
	# pick 
	#for line in cds_lines[first_tx]:
	#	print(line)
	for item in cds_lines.items():
		print(item)
	
	# can't use first exon used for APC, it may not be in frame
	# frame depends on actual first exon, with ATG
	# all this is a waste of time
	# just manually input correct reading frame
	# need to decide on canonical gene structure
		
	# pdr-1 has CDS entries with the same start but different ending
	# how to handle?
	# use a.1 transcripts as first
	'''
			

	'''
		print(cds_beg)
	for iso in locus.isoforms:
		#print(iso)
		#print(iso.rnatype)
		iso.translate(cds_beg)
		print(iso.rnatype)
	'''
	
	
	'''
	with open(arg.fasta, 'rt') as fafp:
		for line in fafp:
			if line.startswith('>'):
				line = line.split(' ')
				if line[4].split('=')[0] == 'Start':
					cds_beg = int(line[4].split('=')[1])
					break
				else:
					# doesn't work with searched gffs in difalt		
					reader = Reader(fasta=arg.fasta, gff=arg.translate)
					region = next(reader)

					# find the canonical start codon (5' atg if there 
					# are more than one listed)
					gene = region.ftable.build_genes()[0]
					txs = gene.transcripts()
					atgs = set()
					for tx in txs:
						cdss = sorted(tx.cdss, key=lambda x: x.beg)
						atgs.add(cdss[0].beg -1)
					cds_beg = sorted(list(atgs))[0]
					break
	'''

	# this doesn't work with truncated genes
	'''
	# examine the isoforms to determine if they are NMD targets
	prevs = [iso.prob for iso in locus.isoforms]
	posts = []
	rtypes = []
	for iso in locus.isoforms:
		iso.translate(cds_beg)
		if   iso.rnatype == 'non-stop':   iso.prob *= arg.nonstop
		elif iso.rnatype == 'nmd-target': iso.prob *= arg.nmd
		posts.append(iso.prob)
		rtypes.append(iso.rnatype)
	# probabilities before adjusting for NMD
	#print(prevs)
	# probabilities after adjusting for NMD
	#print(posts)
	# can be coding, non-stop, or nmd-target
	#print(rtypes)
	'''
	

	
'''
	# recompute probabilities
	total = sum([iso.prob for iso in locus.isoforms])
	for iso in locus.isoforms:
		iso.prob /= total

	locus.write_gff(fp)

else:
	locus.write_gff(fp)
'''










