#!/usr/bin/env python3

import argparse
import os
import isoform
import csv
import copy
import numpy as np

parser = argparse.ArgumentParser(
	description=(
		'Test different distance equations on APC results, '
		'get intron frequencies, created ranked lists'
	)
)
	
parser.add_argument('apc', help='APC generated gff files')
parser.add_argument('smallgenes', 
	help='Directory with WormBase gff/fasta files')
parser.add_argument('--outf', required=False, help='outfile name')

args = parser.parse_args()

if not args.apc.endswith('/'):
	args.apc = args.apc + '/'

if not args.smallgenes.endswith('/'):
	args.smallgenes = args.smallgenes + '/'

gff_paths = {}
for fname in os.listdir(args.apc):
	gid = '.'.join(fname.split('.')[:3])
	gff_paths[gid] = [f'{args.apc}{fname}']
	
def add_zeroes(introns1, introns2):
	
	i1 = copy.deepcopy(introns1)
	i2 = copy.deepcopy(introns2)
	
	for i in i1:
		if i not in i2: i2[i] = 0
	
	for i in i2:
		if i not in i1: i1[i] = 0
		
	i2_sort = {}
	for i in i1:
		i2_sort[i] = i2[i]
		
	return i1, i2_sort
		
for fname in os.listdir(args.smallgenes):
	if fname.endswith('.gff3'):
		gid = '.'.join(fname.split('.')[:3])
		gff_paths[gid].append(f'{args.smallgenes}{fname}')

gene_hists = {}
for gitems in gff_paths.items():
	apc_ints = isoform.get_introns(gitems[1][0])
	wb_ints = isoform.get_introns(gitems[1][1])
	apc_ints0, wb_ints0 = add_zeroes(apc_ints, wb_ints)
	histograms = {}
	for intron in apc_ints0:
		histograms[intron] = (apc_ints0[intron], wb_ints0[intron])
	gene_hists[gitems[0]] = histograms
		
def intersection(histograms):
	
	min_sum = 0
	total = 0
	for item in histograms.items():
		min_sum += min(item[1][0], item[1][1])
		total += item[1][1]
	
	dist = min_sum/total
	
	return dist
		
distances = {}
for gene in gene_hists:
	distances[gene] = intersection(gene_hists[gene])

print(distances)

'''
if args.outf: 
	outname1 = f'{args.outf}.dist'
	outname2 = f'{args.outf}.freq'
else: 
	outname1 = 'out_isodif.dist'
	outname2 = 'out_isodif.freq'
	
with open(outname1, 'w') as csvfile:
	dist_writer = csv.writer(csvfile)
	dist_writer.writerow(['gene_id', 'chebyshev', 'manhattan'])
	for item in distances.items():
		dist_writer.writerow([item[0], item[1][0], item[1][1]])

# intron information is still in fdists
with open(outname2, 'w') as csvfile:
	int_writer = csv.writer(csvfile)
	int_writer.writerow(['gene_id', 'wb', 'apc'])
	for item in frequencies.items():
		for int_info in item[1]:
			int_writer.writerow([item[0], int_info[1], int_info[2]])
'''










