#!/usr/bin/env python3

import argparse
import os
import isoform2
import math
import csv
import copy

parser = argparse.ArgumentParser(
	description=(
		'Test different distance equations on APC results, '
		'get intron frequencies'
	)
)
	
parser.add_argument('apcgen_gffs', help='APC generated gff files')
parser.add_argument('smallgenes', 
	help='Directory with WormBase gff/fasta files')

args = parser.parse_args()

apc = {}
for file in os.listdir(args.apcgen_gffs):
	gid = file.split('.')[1]
	if args.apcgen_gffs.endswith('/'):
		apc[gid] = f'{args.apcgen_gffs}{file}'
	else:
		apc[gid] = f'{args.apcgen_gffs}/{file}'

wb = {}
for file in os.listdir(args.smallgenes):
	gid = file.split('.')[1]
	if file.endswith('.gff3'):
		if args.smallgenes.endswith('/'):
			wb[gid] = f'{args.smallgenes}{file}'
		else:
			wb[gid] = f'{args.smallgenes}/{file}'
	
genes = {}
for gid in apc:
	wb_ints = isoform2.get_introns(wb[gid])
	apc_ints = isoform2.get_introns(apc[gid])
	genes[gid] = (wb_ints, apc_ints)

def add_zeroes(introns1, introns2):
	
	i1 = copy.deepcopy(introns1)
	i2 = copy.deepcopy(introns2)
	
	for i in i1:
		if i not in i2: i2[i] = 0
	
	for i in i2:
		if i not in i1: i1[i] = 0
		
	return i1, i2
	
# do i really need to use deepcopy?
'''
def add_zeroes(introns1, introns2):
	
	for i in introns1:
		if i not in introns2:
			introns2[i] = 0
			
	for i in introns2:
		if i not in introns1:
			introns1[i] = 0		
			
	return introns1, introns2
'''

shared_freqs = {}
# need to come back to this
strange_gids = []
for gid in genes:
	# use wormbase as reference, so you don't miss/make up introns
	ints1, ints2 = add_zeroes(genes[gid][0], genes[gid][1])
	shared_ints = []
	for i in ints1:
		if ints1[i] != 0 and ints2[i] == 0: 
			if gid not in strange_gids: strange_gids.append(gid)
		if ints1[i] != 0 and ints2[i] != 0: 
			shared_ints.append((ints1[i], ints2[i]))
	if len(shared_ints) == 0: print('no share')
	shared_freqs[gid] = shared_ints
	
#for item in shared_freqs.items():#
#	print(item[1][0])

print(len(strange_gids))

print(strange_gids)

i1, i2 = add_zeroes(genes['1_540'][0], genes['1_540'][1])
for i in i1:
	print(i1[i], i2[i], i)



# 3_46 missed intron is canonical and in-bounds, a true miss?
# same for 1_540?










