#!/usr/bin/env python3

import argparse
import glob
import json
import math
import os

# used weighted pwm
import apc_analysis as aa

import openturns as ot  # conda install -y openturns

from grimoire.genome import Reader
import isoform2

def create_length_model(seqs, lmin, lmax):
	# get the lengths
	lens = [len(seq) for seq in seqs]

	# train Frechet
	sample = ot.Sample([[x] for x in lens if x < lmax])
	f = ot.FrechetFactory().buildAsFrechet(sample)
	a = f.getAlpha()
	b = f.getBeta()
	g = f.getGamma()

	# create histogram from frechet
	pdf = []
	for x in range(lmax):
		if x < g: pdf.append(0)
		else:
			z = (x-g)/b
			pdf.append((a/b) * z**(-1-a) * math.exp(-z**-a))

	# create leading zeros and rescale
	for i in range(lmin): pdf[i] = 0
	total = sum(pdf)
	for i in range(len(pdf)): pdf[i] /= total

	return pdf

#######
# CLI #
#######

parser = argparse.ArgumentParser(description='splice model builder')
parser.add_argument('dir', help='path to directory of genes (e.g. smallgenes)')
parser.add_argument('name', help='name of the model (e.g. worm)')
parser.add_argument('out', help='save sub-models to directory (e.g. models)')
parser.add_argument('--alt_splice_sites', required=False, type=str, 
	help='list of donor and acceptor sites to use')
#parser.add_argument('--don', type=int, default=5, help="[%(default)i]")
parser.add_argument('--up2_don', action='store_true', 
	help="include 2 base pairs upstream of GT donor site")
#parser.add_argument('--acc', type=int, default=6, help="[%(default)i]")
parser.add_argument('--emm', type=int, default=3, help="[%(default)i]")
parser.add_argument('--emin', type=int, default=25, help="[%(default)i]")
parser.add_argument('--emax', type=int, default=1000, help="[%(default)i]")
parser.add_argument('--imm', type=int, default=3, help="[%(default)i]")
parser.add_argument('--imin', type=int, default=35, help="[%(default)i]")
parser.add_argument('--imax', type=int, default=1000, help="[%(default)i]")

# pwm parameters
parser.add_argument('--don_len', required=False, type=int, default=5, 
	metavar='<integer>', help='donor site length [%(default)i]')
parser.add_argument('--acc_len', required=False, type=int, default=6, 
	metavar='<integer>', help='acceptor site length [%(default)i]')
parser.add_argument('--don_left', required=False, type=int, default=0, 
	metavar='<integer>', 
	help='get bases on donor site left flank [%(default)i]')
parser.add_argument('--acc_right', required=False, type=int, default=0, 
	metavar='<integer>', 
	help='get bases on acceptor site right flank [%(default)i]')

arg = parser.parse_args()

# shorten arguments for indexing
DN = arg.don_len
AN = arg.acc_len
DL = arg.don_left 
AR = arg.acc_right 

## collect subsequences
rel_accs = []
rel_dons = []
exons = []
introns = []
exonsum = 0
for ff in glob.glob(f'{arg.dir}/*.fa'):
	gf = ff[:-2] + 'gff3'
	genome = Reader(gff=gf, fasta=ff)
	chrom = next(genome)
	gene = chrom.ftable.build_genes()[0]
	tx = gene.transcripts()[0]
	gseq = gene.seq_str()
	for f in tx.exons:
		# shorten exon by 2 bp if using longer donor site
		if arg.up2_don:
			exons.append(f.seq_str()[:-2])
			exonsum += f.end - f.beg + 1 -2
		else:
			exons.append(f.seq_str())
			exonsum += f.end - f.beg + 1
			
	# get scored introns from rnaseq
	total_score = 0
	don_acc_sites = []
	for f in chrom.ftable.features:
		if f.source == 'RNASeq_splice':
			total_score += f.score
			don = gseq[f.beg-100-DL:f.beg-100+DN]
			acc = gseq[f.end-99-AN:f.end-99+AR]
			don_acc = (don, acc, f.score)
			don_acc_sites.append(don_acc)
			
	# get relative counts
	for sites in don_acc_sites:
		rdon = [sites[0], sites[2] / total_score]
		racc = [sites[1], sites[2] / total_score]
		rel_dons.append(rdon)
		rel_accs.append(racc)

	# get wormbase annotated introns for length model
	# length model doesn't have weights
	for f in tx.introns:
		introns.append(f.seq_str())

'''
# one-count based method
# need to use weighted introns instead
accs = []
dons = []
exons = []
introns = []
exonsum = 0
for ff in glob.glob(f'{arg.dir}/*.fa'):
	gf = ff[:-2] + 'gff3'
	genome = Reader(gff=gf, fasta=ff)
	tx = next(genome).ftable.build_genes()[0].transcripts()[0]
	for f in tx.exons:
		if arg.up2_don:
			exons.append(f.seq_str()[:-2])
			exonsum += f.end - f.beg + 1 -2
		else:
			exons.append(f.seq_str())
			exonsum += f.end - f.beg + 1
	for i, f in enumerate(tx.introns):
		iseq = f.seq_str()
		if arg.up2_don:
			# offset coordinates by 100 bp flank
			ex_end = wb_exons[i][1]-99
			up_dseq = tx.seq_str()[ex_end-2:f.beg-100+arg.don_len]
			dons.append(up_dseq)
		else:
			dons.append(iseq[0:arg.don_len])
		accs.append(iseq[-arg.acc_len:])
		introns.append(iseq)
'''

'''
# might finish this later
# used input file with donor/acceptor/intron sequences instead
if arg.alt_splice_sites:
	
	dons = []
	accs = []
	with open(arg.alt_splice_sites, 'r') as fp:
		for line in fp:
			line = line.rstrip()
			line = line.split(',')
			dons.append(line[0])
			accs.append(line[1])	
'''	

##### Strange behavior #####
# i get a key error in geniso2/isoform2.py 
# as well as the original geniso/isoform.py
# for the mm when training the models only on fewgenes/
# training on all of smallgenes is fine
# not sure why, hopefully won't create issues later
# prob something to do with lack of data for training

## build models
inf = len(introns) / exonsum
#acc = isoform2.create_pwm(accs)
#don = isoform2.create_pwm(dons)
acc = aa.build_weighted_pwm(rel_dons, len(rel_dons[0][0]))
don = aa.build_weighted_pwm(rel_accs, len(rel_accs[0][0]))
exs = isoform2.create_markov(exons, arg.emm, 0, 0)
ins = isoform2.create_markov(introns, arg.imm, arg.don_len, arg.acc_len)
exl = create_length_model(exons, arg.emin, arg.emax)
inl = create_length_model(introns, arg.imin, arg.imax)

## write individual models (hard-coded names)
facc = f'{arg.out}/acc.pwm'
fdon = f'{arg.out}/don.pwm'
fexs = f'{arg.out}/exon.mm'
fins = f'{arg.out}/intron.mm'
fexl = f'{arg.out}/exon.len'
finl = f'{arg.out}/intron.len'
finf = f'{arg.out}/intron.freq'
if not os.path.exists(arg.out): os.makedirs(arg.out)
isoform2.write_pwm(facc, acc)
isoform2.write_pwm(fdon, don)
isoform2.write_markov(fexs, exs)
isoform2.write_markov(fins, ins)
isoform2.write_len(fexl, exl)
isoform2.write_len(finl, inl)
with open(finf, 'w') as fp: print(inf, file=fp)

# write ghmm
if arg.up2_don:
	ghmm = {
		'name': arg.name,
		'inf': isoform2.prob2score(inf),
		'acc': isoform2.read_pwm(facc),
		'up2_don': isoform2.read_pwm(fdon),
		'exs': isoform2.read_markov(fexs),
		'ins': isoform2.read_markov(fins),
		'exl': isoform2.read_len(fexl),
		'inl': isoform2.read_len(finl),
	}
else:
	ghmm = {
		'name': arg.name,
		'inf': isoform2.prob2score(inf),
		'acc': isoform2.read_pwm(facc),
		'don': isoform2.read_pwm(fdon),
		'exs': isoform2.read_markov(fexs),
		'ins': isoform2.read_markov(fins),
		'exl': isoform2.read_len(fexl),
		'inl': isoform2.read_len(finl),
	}	
	
print(json.dumps(ghmm, indent=1))



